name: 'Github PR Attestation Action'
icon: 'check-circle'
color: 'red'
description: 'C'
inputs:
  private-key:
    description: 'The private key to use for signing and submitting attestation transactions.'
    required: true
  network:
    description: 'The ethereum network to use. Options are: "sepolia"'
    required: true
  rpc-url:
    description: 'The RPC URL to use.'
    required: false
  branch:
    description: 'The main branch to trigger attestations on when PR is merged.'
    required: false
  branches:
    description: 'A list of main branches'
    required: false
outputs:
  hash:
    description: 'Transaction hash of the attestation submission.'
  uid:
    description: 'UID of the attestation.'
runs:
  using: 'node16'
  main: 'dist/index.js'
